version: '3'
services:
  dashboard:
    build: .
    container_name: dashboard
    command: bash
    tty: true
    stdin_open: true
    user: app
    volumes:
      - ~/.ssh:/home/app/.ssh
      - .:/usr/src/app
      - dashboardbundle:/bundle
    tmpfs:
      - /usr/src/app/tmp/pids:mode=777,size=4m,uid=1000,gid=1000
    ports:
      - "3000:3000"
      - "3035:3035"
      - "35729:35729"
    depends_on:
      - dashboarddb
    environment: 
      TZ: America/New_York
      PGHOST: dashboarddb
      PGUSER: postgres
  dashboarddb:
    image: postgres
    container_name: dashboarddb
    volumes:
      - dashboarddata:/var/lib/postgresql/data
    environment:
      TZ: America/New_York
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:
volumes:
  dashboardbundle:
    external: true
  dashboarddata:
    external: true